# Generated by Django 5.2.5 on 2026-04-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mission_title', models.CharField(max_length=255)),
                ('mission_content', models.TextField()),
                ('vision_title', models.CharField(max_length=255)),
                ('vision_content', models.TextField()),
                ('years_of_excellence', models.IntegerField()),
                ('companies_count_text', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], max_length=20)),
                ('image_url', models.URLField()),
                ('expert', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('primary_cta_text', models.CharField(max_length=100)),
                ('primary_cta_link', models.URLField()),
                ('secondary_cta_text', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_link', models.URLField(blank=True)),
                ('background_image_url', models.URLField()),
                ('stats', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_subtitle', models.CharField(max_length=255)),
                ('section_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cta_button_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_subtitle', models.CharField(max_length=255)),
                ('section_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_subtitle', models.CharField(max_length=255)),
                ('section_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('chart', 'Chart'), ('code', 'Code')], max_length=50)),
                ('gradient', models.CharField(max_length=100)),
                ('features', models.JSONField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.servicesection')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
                ('deliverables', models.JSONField()),
                ('how_it_works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.howitworks')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('testimonial', models.TextField()),
                ('rating', models.IntegerField()),
                ('gradient', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='core.testimonialsection')),
            ],
        ),
    ]
