# Generated by Django 5.2.5 on 2026-04-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blog_status_alter_comment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('gradient', models.CharField(max_length=100)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('impact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.story'),
        ),
        migrations.CreateModel(
            name='StoryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.story')),
            ],
        ),
    ]
