# Generated by Django 5.2.5 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_alter_comment_post_comment_story_storyresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='story',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='2', max_length=254),
            preserve_default=False,
        ),
    ]
