# Generated by Django 5.2.5 on 2026-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_comment_full_name_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='comment',
            name='Company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
